server:
  port: 8080

spring:
  application:
    name: ovo
  main:
    banner-mode: "off"
    web-application-type: servlet
  sql:
    init:
      mode: embedded

  datasource:
#    url: jdbc:postgresql://postgresqlflexibletest.postgres.database.azure.com:5432/demo?sslmode=require
#    username: <your_postgresql_ad_non_admin_username>
#    azure:
#      passwordless-enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/


